global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.15.0.6:9100']
        labels:
          env: 'staging'
      - targets: ['10.15.0.5:9100']
        labels:
          env: 'production'

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.15.0.6:3001']
        labels:
          env: 'staging'
      - targets: ['10.15.0.5:3001']
        labels:
          env: 'production'

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.15.0.6:3002']
        labels:
          env: 'staging'
      - targets: ['10.15.0.5:3002']
        labels:
          env: 'production'

  - job_name: 'inventory-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.15.0.6:3003']
        labels:
          env: 'staging'
      - targets: ['10.15.0.5:3003']
        labels:
          env: 'production'
