name: Deploy App Stack (Staging)

on:
  push:
    branches:
      - staging
    paths:
      - 'infra/app-host/**'
      - 'services/**'
      - '.github/workflows/deploy-staging.yml'

jobs:
  deploy:
    name: Deploy to Staging VM
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |

            mkdir -p /app/infra/app-host
            cd /app/infra/app-host
            git checkout staging
            git pull || (git clone -b staging https://github.com/${{ github.repository }}.git /app && cd /app/infra/app-host)
            echo "ENV_NAME=staging" > .env
            echo "MONITORING_VM_PRIVATE_IP=${{ secrets.MONITORING_VM_PRIVATE_IP }}" >> .env
            docker compose down
            docker compose up -d --build

