name: Deploy App Stack (Production)

on:
  push:
    branches:
      - production
    paths:
      - 'infra/app-host/**'
      - 'services/**'
      - '.github/workflows/deploy-production.yml'

jobs:
  deploy:
    name: Deploy to Production VM
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |

            if [ ! -d "/app/.git" ]; then
              rm -rf /app
              git clone -b production https://github.com/${{ github.repository }}.git /app
            fi
            cd /app/infra/app-host
            git fetch origin
            git checkout production
            git pull origin production
            echo "ENV_NAME=production" > .env
            echo "MONITORING_VM_PRIVATE_IP=${{ secrets.MONITORING_VM_PRIVATE_IP }}" >> .env
            docker compose down
            docker compose up -d --build


