name: Deploy Monitoring Stack

on:
  push:
    branches:
      - main
    paths:
      - 'infra/monitoring/**'
      - '.github/workflows/deploy-monitor.yml'

jobs:
  deploy:
    name: Deploy to Central Monitor VM
    runs-on: ubuntu-latest
    environment: monitoring
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |

            if [ ! -d "/app/.git" ]; then
              rm -rf /app
              git clone https://github.com/${{ github.repository }}.git /app
            fi
            cd /app/infra/monitoring
            git fetch origin
            git checkout main
            git pull origin main
            echo "MONITORING_VM_PRIVATE_IP=${{ secrets.MONITORING_VM_PRIVATE_IP }}" > .env
            docker compose pull
            docker compose up -d
